// AUTO-GENERATED by scripts/build-seg-phrases.mjs — do not edit by hand.
//
// Entries in lexicon-th.js that human linguists treat as MORE THAN ONE WORD.
// segment.js removes them, so ฝนตกหนัก parses ฝน|ตก|หนัก instead of ฝน|ตกหนัก
// and stops glossing heavy rain as "shoulder a burden".
//
// 143 entries, each cut through in running text at least 20 times and
// at least 80% of the time. 36 further candidates were EXCLUDED
// because the course teaches them as vocabulary (ขายดี, คืนนี้, คืนเงิน, จัดให้, ดีมาก, ตอนที่…):
// Paste Text must not disagree with the flashcard about the same word.
//
// A FLOOR, NOT A VERDICT. Only 3814 of the 12253 lexicon entries occur
// often enough here to judge at all; the rest are unaudited, not endorsed.
//
// ── LICENCE ────────────────────────────────────────────────────────────────
// Derived from VISTEC-TP-TH-2021 by Limkonchotiwat, Phatthiyaphaibun,
// Sarwar, Chuangsuwanich and Nutanong (ACL-IJCNLP 2021),
//   https://github.com/mrpeerat/OSKut/tree/main/VISTEC-TP-TH-2021
// licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
// THIS FILE is therefore also CC BY-SA 3.0 and any redistribution must keep
// this notice. Kept separate from lexicon-th.js — which is CC0 and stays that
// way — so each file's notice is exactly true of that file and of nothing
// else, the same boundary gloss-th.js and gloss-vol.js hold.

var SEG_PHRASES = "กลับบ้าน\nกล่าวถึง\nกันเอา\nกำลังดี\nกินที่\nกินน้ำ\nก็ช่าง\nก็ดี\nก็แล้วแต่\nก็ได้\nก่อนหน้านี้\nขณะนี้\nขับรถ\nขั้นต่ำ\nข้างใน\nคนใช้\nคนใน\nจริงอยู่\nจัดงาน\nจากนี้\nชื่อว่า\nดีแล้ว\nดีไม่ดี\nดูก่อน\nดูเหมือน\nด้านหน้า\nตกหนัก\nตกเป็น\nตรงกลาง\nตรงกัน\nตรงนี้\nตลอดจน\nตอนนั้น\nตอนหลัง\nตอนเช้า\nตอนเย็น\nตอนแรก\nตัดผม\nติดอันดับ\nต่อมา\nต่อไปนี้\nต้องสู้\nต้องหา\nถึงกัน\nถึงกับ\nถึงขนาด\nถึงที่\nถือว่า\nถ่ายภาพ\nทั้งคน\nทั้งคู่\nทำการบ้าน\nทำหน้าที่\nทำเงิน\nทำเป็น\nทำเอา\nทีละ\nที่ทาง\nที่ผ่านมา\nที่มา\nที่วัด\nที่อยู่\nที่แท้\nที่แล้ว\nทุกที\nทุกสิ่งทุกอย่าง\nนับว่า\nนี่เอง\nนึกออก\nประกอบด้วย\nพร้อมกับ\nพวกเรา\nพอกัน\nพอดู\nพอใช้\nพูดถึง\nฟังได้\nมันดี\nมาตี\nมานะ\nมายัง\nมีชื่อ\nมีหน้า\nมีอายุ\nมีเสียง\nยกมือ\nยึดอำนาจ\nยื่นมือ\nรวดเดียว\nรู้มาก\nรู้อยู่\nลดเหลือ\nลองดู\nล้างมือ\nวันที่\nว่าที่\nว่ายาก\nสักหน่อย\nสั่งงาน\nสั่งซื้อ\nส่งผล\nส่วนมาก\nส่วนใหญ่\nหน้าเป็น\nหรือไม่\nหลังจากนั้น\nหันหน้า\nหันหลัง\nหาเงิน\nหาไม่\nอยู่ตัว\nอย่างเช่น\nอีกหน่อย\nเขียนแบบ\nเข้าสู่\nเงินได้\nเช่นนี้\nเตือนสติ\nเท่าตัว\nเท่านี้\nเป็นอัน\nเป็นได้\nเพราะว่า\nเหมือนกับ\nเหมือนว่า\nเหมือนเดิม\nเหล่านั้น\nเหล่านี้\nเอาจริง\nเอาชื่อ\nเอาหน้า\nแค่นั้น\nแค่นี้\nแต่ว่า\nแล้วก็\nแล้วด้วย\nใจมา\nใช้ได้\nในที่นี้\nได้ชื่อ\nได้ที่\nไม่ค่อย\nไม่เชิง";
