// All Thai data — words, consonants, vowels, tones. This file is the source of truth.
// (Originally generated from a Python app that has since been removed.)

const CONSONANTS = [
  ["ก", "k", "mid", "ไก่", "k", "k"],
  ["ข", "kh", "high", "ไข่", "kh", "k"],
  ["ค", "kh", "low", "ควาย", "kh", "k"],
  ["ง", "ng", "low", "งู", "ng", "ng"],
  ["จ", "ch", "mid", "จาน", "ch", "t"],
  ["ช", "ch", "low", "ช้าง", "ch", "t"],
  ["ซ", "s", "low", "โซ่", "s", "t"],
  ["ญ", "y", "low", "หญิง", "y", "n"],
  ["ด", "d", "mid", "เด็ก", "d", "t"],
  ["ต", "t", "mid", "เต่า", "t", "t"],
  ["ถ", "th", "high", "ถุง", "th", "t"],
  ["ท", "th", "low", "ทหาร", "th", "t"],
  ["น", "n", "low", "หนู", "n", "n"],
  ["บ", "b", "mid", "ใบไม้", "b", "p"],
  ["ป", "p", "mid", "ปลา", "p", "p"],
  ["ผ", "ph", "high", "ผึ้ง", "ph", "-"],
  ["ฝ", "f", "high", "ฝา", "f", "-"],
  ["พ", "ph", "low", "พาน", "ph", "p"],
  ["ฟ", "f", "low", "ฟัน", "f", "p"],
  ["ภ", "ph", "low", "สำเภา", "ph", "p"],
  ["ม", "m", "low", "ม้า", "m", "m"],
  ["ย", "y", "low", "ยักษ์", "y", "y"],
  ["ร", "r", "low", "เรือ", "r", "n"],
  ["ล", "l", "low", "ลิง", "l", "n"],
  ["ว", "w", "low", "แหวน", "w", "w"],
  ["ศ", "s", "high", "ศาลา", "s", "t"],
  ["ส", "s", "high", "เสือ", "s", "t"],
  ["ห", "h", "high", "หีบ", "h", "-"],
  ["อ", "o", "mid", "อ่าง", "-", "-"],
  ["ฮ", "h", "low", "นกฮูก", "h", "-"],
  ["ฉ", "ch", "high", "ฉิ่ง", "ch", "-"],
  ["ฌ", "ch", "low", "เฌอ", "ch", "-"],
  ["ฏ", "d", "mid", "ชฎา", "d", "t"],
  ["ฐ", "th", "high", "ฐาน", "th", "t"],
  ["ฑ", "th", "low", "มณโฑ", "th", "t"],
  ["ฒ", "th", "low", "ผู้เฒ่า", "th", "t"],
  ["ณ", "n", "low", "เณร", "n", "n"],
  ["ฎ", "d", "mid", "ชฎา", "d", "t"],
  ["ธ", "th", "low", "ธง", "th", "t"],
  ["ฬ", "l", "low", "จุฬา", "l", "n"],
  ["ฆ", "kh", "low", "ระฆัง", "kh", "k"],
];

const VOWELS = [
  ["◌า", "aa", "long a", "มา (maa) = come"],
  ["◌ิ", "i", "short i", "นิด (nit) = a little"],
  ["◌ี", "ii", "long i", "นี้ (nii) = this"],
  ["◌ึ", "ue", "short ue", "กึ่ง (kueeng) = half"],
  ["◌ื", "uue", "long ue", "มืด (muuet) = dark"],
  ["◌ุ", "u", "short u", "กุ้ง (kung) = shrimp"],
  ["◌ู", "uu", "long u", "ดู (duu) = look"],
  ["เ◌", "ee", "long e", "เก (kee) = old"],
  ["แ◌", "ae", "long ae", "แมว (maew) = cat"],
  ["โ◌", "oo", "long o", "โต (too) = big"],
  ["◌อ", "oo", "short o", "กอ (koo) = embrace"],
  ["เ◌าะ", "o", "short o", "เกาะ (ko) = island"],
  ["◌ัว", "ua", "ua vowel", "กัว (kua) = to confuse"],
  ["เ◌ีย", "ia", "ia vowel", "เมีย (mia) = wife"],
  ["เ◌ือ", "uea", "uea vowel", "เมือง (muueang) = city"],
  ["◌ำ", "am", "am vowel", "น้ำ (naam) = water"],
  ["ไ◌", "ai", "ai vowel", "ไป (pai) = go"],
  ["ใ◌", "ai", "ai vowel 2", "ใจ (jai) = heart"],
  ["เ◌า", "ao", "ao vowel", "เขา (khao) = he/she"],
];

const TONES = [
  ["สามัญ", "mid", "normal tone — no mark", "กา (kaa) = crow"],
  ["เอก", "low", "falling tone — ่", "ข่า (khàa) = galangal"],
  ["โท", "falling", "falling from high — ้", "ข้า (khâa) = servant"],
  ["ตรี", "high", "high tone — ๊", "ค๊าน — rare"],
  ["จัตวา", "rising", "rising tone — ๋", "ค๋าน — rare"],
];

const TONE_CLASSES = {
  "mid": ["ก", "จ", "ด", "ต", "บ", "ป", "อ", "ฏ", "ฎ"],
  "high": ["ข", "ฉ", "ถ", "ผ", "ฝ", "ศ", "ษ", "ส", "ห", "ฐ"],
  "low": ["ค", "ง", "ช", "ซ", "ญ", "ณ", "น", "ม", "ย", "ร", "ล", "ว", "ฆ", "ฌ", "ฑ", "ฒ", "ธ", "ภ", "พ", "ฟ", "ฬ", "ฮ"],
};

const WORDS = [
  ["ฉัน", "chǎn", "I (female)", "pronoun", "pronouns"],
  ["ผม", "phǒm", "I (male)", "pronoun", "pronouns"],
  ["คุณ", "khun", "you", "pronoun", "pronouns"],
  ["เขา", "khǎo", "he/she/they", "pronoun", "pronouns"],
  ["เรา", "rao", "we/I (informal)", "pronoun", "pronouns"],
  ["พวกเขา", "phûak khǎo", "they", "pronoun", "pronouns"],
  ["มัน", "man", "it", "pronoun", "pronouns"],
  ["นี้", "níi", "this", "demonstrative", "pronouns"],
  ["นั้น", "nán", "that", "demonstrative", "pronouns"],
  ["อะไร", "à-rai", "what", "question", "pronouns"],
  ["ใคร", "khrai", "who", "question", "pronouns"],
  ["ที่ไหน", "thîi-nǎi", "where", "question", "pronouns"],
  ["เมื่อไร", "mûea-rai", "when", "question", "pronouns"],
  ["ทำไม", "tham-mai", "why", "question", "pronouns"],
  ["อย่างไร", "yàang-rai", "how", "question", "pronouns"],
  ["หนึ่ง", "nùeng", "one", "number", "numbers"],
  ["สอง", "sǒong", "two", "number", "numbers"],
  ["สาม", "sǎam", "three", "number", "numbers"],
  ["สี่", "sìi", "four", "number", "numbers"],
  ["ห้า", "hâa", "five", "number", "numbers"],
  ["หก", "hòk", "six", "number", "numbers"],
  ["เจ็ด", "jèt", "seven", "number", "numbers"],
  ["แปด", "pàet", "eight", "number", "numbers"],
  ["เก้า", "kâo", "nine", "number", "numbers"],
  ["สิบ", "sìp", "ten", "number", "numbers"],
  ["ร้อย", "rói", "hundred", "number", "numbers"],
  ["พัน", "phan", "thousand", "number", "numbers"],
  ["หมื่น", "mùuen", "ten thousand", "number", "numbers"],
  ["แสน", "sǎen", "hundred thousand", "number", "numbers"],
  ["ล้าน", "láan", "million", "number", "numbers"],
  ["เป็น", "pen", "to be", "verb", "verbs_core"],
  ["มี", "mii", "to have/there is", "verb", "verbs_core"],
  ["ไป", "pai", "to go", "verb", "verbs_core"],
  ["มา", "maa", "to come", "verb", "verbs_core"],
  ["ทำ", "tham", "to do/make", "verb", "verbs_core"],
  ["บอก", "bòok", "to tell/say", "verb", "verbs_core"],
  ["พูด", "phûut", "to speak", "verb", "verbs_core"],
  ["กิน", "kin", "to eat", "verb", "verbs_core"],
  ["ดื่ม", "dùuem", "to drink", "verb", "verbs_core"],
  ["นอน", "noon", "to sleep", "verb", "verbs_core"],
  ["ตื่น", "tùuen", "to wake up", "verb", "verbs_core"],
  ["นั่ง", "nâng", "to sit", "verb", "verbs_core"],
  ["ยืน", "yuuen", "to stand", "verb", "verbs_core"],
  ["เดิน", "dooen", "to walk", "verb", "verbs_core"],
  ["วิ่ง", "wîng", "to run", "verb", "verbs_core"],
  ["ดู", "duu", "to look/watch", "verb", "verbs_core"],
  ["เห็น", "hěn", "to see", "verb", "verbs_core"],
  ["ฟัง", "fang", "to listen", "verb", "verbs_core"],
  ["ได้ยิน", "dâi-yin", "to hear", "verb", "verbs_core"],
  ["รู้", "rúu", "to know (fact)", "verb", "verbs_core"],
  ["รู้จัก", "rúu-jàk", "to know (person)", "verb", "verbs_core"],
  ["เข้าใจ", "khâo-jai", "to understand", "verb", "verbs_core"],
  ["คิด", "khít", "to think", "verb", "verbs_core"],
  ["ต้องการ", "tông-kaan", "to want/need", "verb", "verbs_core"],
  ["อยาก", "yàak", "to want", "verb", "verbs_core"],
  ["ชอบ", "chôop", "to like", "verb", "verbs_core"],
  ["รัก", "rák", "to love", "verb", "verbs_core"],
  ["เกลียด", "klìat", "to hate", "verb", "verbs_core"],
  ["ให้", "hâi", "to give", "verb", "verbs_core"],
  ["รับ", "ráp", "to receive", "verb", "verbs_core"],
  ["ซื้อ", "súue", "to buy", "verb", "verbs_core"],
  ["ขาย", "khǎai", "to sell", "verb", "verbs_core"],
  ["เปิด", "pòoet", "to open", "verb", "verbs_core"],
  ["ปิด", "pìt", "to close", "verb", "verbs_core"],
  ["เริ่ม", "rôoem", "to start", "verb", "verbs_core"],
  ["จบ", "jòp", "to finish/end", "verb", "verbs_core"],
  ["ช่วย", "chûay", "to help", "verb", "verbs_core"],
  ["ถาม", "thǎam", "to ask", "verb", "verbs_core"],
  ["ตอบ", "tòop", "to answer", "verb", "verbs_core"],
  ["อ่าน", "àan", "to read", "verb", "verbs_core"],
  ["เขียน", "khǐan", "to write", "verb", "verbs_core"],
  ["เรียน", "rian", "to study/learn", "verb", "verbs_core"],
  ["สอน", "sǒon", "to teach", "verb", "verbs_core"],
  ["เล่น", "lên", "to play", "verb", "verbs_core"],
  ["ทำงาน", "tham-ngaan", "to work", "verb", "verbs_core"],
  ["ใช้", "chái", "to use", "verb", "verbs_core"],
  ["เอา", "ao", "to take/get", "verb", "verbs_core"],
  ["วาง", "waang", "to put/place", "verb", "verbs_core"],
  ["เอาออก", "ao-òok", "to take out", "verb", "verbs_core"],
  ["เปลี่ยน", "plìian", "to change", "verb", "verbs_core"],
  ["หา", "hǎa", "to find/look for", "verb", "verbs_core"],
  ["ลืม", "luuem", "to forget", "verb", "verbs_core"],
  ["จำ", "jam", "to remember", "verb", "verbs_core"],
  ["รอ", "roo", "to wait", "verb", "verbs_core"],
  ["มาถึง", "maa-thǔeng", "to arrive", "verb", "verbs_core"],
  ["ออกไป", "òok-pai", "to leave/go out", "verb", "verbs_core"],
  ["กลับ", "klàp", "to return", "verb", "verbs_core"],
  ["อยู่", "yùu", "to be at/to stay", "verb", "verbs_core"],
  ["อาศัย", "aa-sǎi", "to live/reside", "verb", "verbs_core"],
  ["เกิด", "kòoet", "to be born/happen", "verb", "verbs_core"],
  ["ตาย", "taai", "to die", "verb", "verbs_core"],
  ["ได้", "dâi", "to get/can (aux)", "verb", "verbs_aux"],
  ["ต้อง", "tông", "must/have to", "verb", "verbs_aux"],
  ["ควร", "khuuan", "should", "verb", "verbs_aux"],
  ["น่าจะ", "nâa-jà", "probably/should", "verb", "verbs_aux"],
  ["จะ", "jà", "will (future)", "verb", "verbs_aux"],
  ["กำลัง", "kam-lang", "currently doing", "verb", "verbs_aux"],
  ["เคย", "khoei", "used to/ever", "verb", "verbs_aux"],
  ["ยัง", "yang", "still/yet", "adverb", "adverbs"],
  ["ดี", "dii", "good", "adjective", "adjectives"],
  ["ไม่ดี", "mâi-dii", "not good/bad", "adjective", "adjectives"],
  ["เลว", "leo", "bad/evil", "adjective", "adjectives"],
  ["ใหม่", "mài", "new", "adjective", "adjectives"],
  ["เก่า", "kào", "old (thing)", "adjective", "adjectives"],
  ["แก่", "kàe", "old (person)", "adjective", "adjectives"],
  ["ใหญ่", "yài", "big", "adjective", "adjectives"],
  ["เล็ก", "lék", "small", "adjective", "adjectives"],
  ["ยาว", "yaao", "long", "adjective", "adjectives"],
  ["สั้น", "sân", "short", "adjective", "adjectives"],
  ["สูง", "sǔung", "tall/high", "adjective", "adjectives"],
  ["เตี้ย", "tîa", "short (height)", "adjective", "adjectives"],
  ["หนัก", "nàk", "heavy", "adjective", "adjectives"],
  ["เบา", "bao", "light (weight)", "adjective", "adjectives"],
  ["เร็ว", "reo", "fast", "adjective", "adjectives"],
  ["ช้า", "cháa", "slow", "adjective", "adjectives"],
  ["ร้อน", "rón", "hot", "adjective", "adjectives"],
  ["เย็น", "yen", "cool/cold", "adjective", "adjectives"],
  ["หนาว", "nǎao", "cold (weather)", "adjective", "adjectives"],
  ["อุ่น", "ùn", "warm", "adjective", "adjectives"],
  ["สวย", "sǔay", "beautiful", "adjective", "adjectives"],
  ["หล่อ", "lòo", "handsome", "adjective", "adjectives"],
  ["น่าเกลียด", "nâa-klìat", "ugly", "adjective", "adjectives"],
  ["อร่อย", "à-ròi", "delicious", "adjective", "adjectives"],
  ["อร่อยมาก", "à-ròi-mâak", "very delicious", "adjective", "adjectives"],
  ["หวาน", "wǎan", "sweet", "adjective", "adjectives"],
  ["เค็ม", "khem", "salty", "adjective", "adjectives"],
  ["เปรี้ยว", "prîao", "sour", "adjective", "adjectives"],
  ["ขม", "khǒm", "bitter", "adjective", "adjectives"],
  ["เผ็ด", "phèt", "spicy", "adjective", "adjectives"],
  ["มีความสุข", "mii-khwaam-sùk", "happy", "adjective", "adjectives"],
  ["เศร้า", "sâo", "sad", "adjective", "adjectives"],
  ["โกรธ", "krôot", "angry", "adjective", "adjectives"],
  ["กลัว", "klua", "afraid/scared", "adjective", "adjectives"],
  ["เหนื่อย", "nùueai", "tired", "adjective", "adjectives"],
  ["หิว", "hǐu", "hungry", "adjective", "adjectives"],
  ["อิ่ม", "ìm", "full (from eating)", "adjective", "adjectives"],
  ["ง่วง", "ngûang", "sleepy", "adjective", "adjectives"],
  ["เจ็บ", "jèp", "to hurt/painful", "adjective", "adjectives"],
  ["ป่วย", "pùuai", "sick", "adjective", "adjectives"],
  ["แข็งแรง", "khǎeng-raeng", "healthy/strong", "adjective", "adjectives"],
  ["รวย", "ruuay", "rich", "adjective", "adjectives"],
  ["จน", "jon", "poor", "adjective", "adjectives"],
  ["ฉลาด", "chà-làat", "smart/clever", "adjective", "adjectives"],
  ["โง่", "ngôo", "stupid", "adjective", "adjectives"],
  ["ง่าย", "ngâai", "easy", "adjective", "adjectives"],
  ["ยาก", "yâak", "difficult", "adjective", "adjectives"],
  ["ถูก", "thùuk", "cheap/correct", "adjective", "adjectives"],
  ["แพง", "phaeng", "expensive", "adjective", "adjectives"],
  ["ฟรี", "frii", "free (no cost)", "adjective", "adjectives"],
  ["เต็ม", "tem", "full (capacity)", "adjective", "adjectives"],
  ["ว่าง", "wâang", "empty/free (time)", "adjective", "adjectives"],
  ["สะอาด", "sà-àat", "clean", "adjective", "adjectives"],
  ["สกปรก", "sòk-kà-pròk", "dirty", "adjective", "adjectives"],
  ["เงียบ", "ngîap", "quiet", "adjective", "adjectives"],
  ["เสียงดัง", "sǐang-dang", "noisy/loud", "adjective", "adjectives"],
  ["สำคัญ", "sǎm-khan", "important", "adjective", "adjectives"],
  ["จำเป็น", "jam-pen", "necessary", "adjective", "adjectives"],
  ["จริง", "jing", "true/real", "adjective", "adjectives"],
  ["เท็จ", "thét", "false/untrue", "adjective", "adjectives"],
  ["พ่อ", "phôo", "father", "noun", "family"],
  ["แม่", "mâe", "mother", "noun", "family"],
  ["พี่ชาย", "phîi-chaai", "older brother", "noun", "family"],
  ["น้องชาย", "nóong-chaai", "younger brother", "noun", "family"],
  ["พี่สาว", "phîi-sǎao", "older sister", "noun", "family"],
  ["น้องสาว", "nóong-sǎao", "younger sister", "noun", "family"],
  ["ลูก", "lûuk", "child/son/daughter", "noun", "family"],
  ["ลูกชาย", "lûuk-chaai", "son", "noun", "family"],
  ["ลูกสาว", "lûuk-sǎao", "daughter", "noun", "family"],
  ["ปู่", "pùu", "paternal grandfather", "noun", "family"],
  ["ย่า", "yâa", "paternal grandmother", "noun", "family"],
  ["ตา", "taa", "maternal grandfather", "noun", "family"],
  ["ยาย", "yaai", "maternal grandmother", "noun", "family"],
  ["สามี", "sǎa-mii", "husband", "noun", "family"],
  ["ภรรยา", "phan-rá-yaa", "wife", "noun", "family"],
  ["ครอบครัว", "khrôop-khrua", "family", "noun", "family"],
  ["หัว", "hǔa", "head", "noun", "body"],
  ["หน้า", "nâa", "face", "noun", "body"],
  ["หู", "hǔu", "ear", "noun", "body"],
  ["จมูก", "jà-mùuk", "nose", "noun", "body"],
  ["ปาก", "pàak", "mouth", "noun", "body"],
  ["ฟัน", "fan", "tooth/teeth", "noun", "body"],
  ["ลิ้น", "lín", "tongue", "noun", "body"],
  ["คอ", "khoo", "neck/throat", "noun", "body"],
  ["ไหล่", "lài", "shoulder", "noun", "body"],
  ["แขน", "khǎen", "arm", "noun", "body"],
  ["มือ", "muue", "hand", "noun", "body"],
  ["นิ้ว", "níu", "finger", "noun", "body"],
  ["หน้าอก", "nâa-òk", "chest", "noun", "body"],
  ["ท้อง", "thóong", "stomach/belly", "noun", "body"],
  ["หลัง", "lǎng", "back", "noun", "body"],
  ["ขา", "khǎa", "leg", "noun", "body"],
  ["เข่า", "khào", "knee", "noun", "body"],
  ["เท้า", "tháo", "foot", "noun", "body"],
  ["นิ้วเท้า", "níu-tháo", "toe", "noun", "body"],
  ["หัวใจ", "hǔa-jai", "heart", "noun", "body"],
  ["เลือด", "lûueat", "blood", "noun", "body"],
  ["กระดูก", "krà-duuk", "bone", "noun", "body"],
  ["ผิวหนัง", "phǐu-nǎng", "skin", "noun", "body"],
  ["ข้าว", "khâao", "rice/food", "noun", "food"],
  ["น้ำ", "náam", "water", "noun", "food"],
  ["อาหาร", "aa-hǎan", "food", "noun", "food"],
  ["เนื้อ", "núuea", "meat", "noun", "food"],
  ["ปลา", "plaa", "fish", "noun", "food"],
  ["ไก่", "kài", "chicken", "noun", "food"],
  ["หมู", "mǔu", "pork/pig", "noun", "food"],
  ["วัว", "wua", "cow/beef", "noun", "food"],
  ["ผัก", "phàk", "vegetable", "noun", "food"],
  ["ผลไม้", "phǒn-lá-mái", "fruit", "noun", "food"],
  ["ไข่", "kài", "egg", "noun", "food"],
  ["นม", "nom", "milk", "noun", "food"],
  ["ชา", "chaa", "tea", "noun", "food"],
  ["กาแฟ", "kaa-fae", "coffee", "noun", "food"],
  ["เบียร์", "bia", "beer", "noun", "food"],
  ["เหล้า", "lâo", "alcohol/liquor", "noun", "food"],
  ["ขนมปัง", "khà-nǒm-pang", "bread", "noun", "food"],
  ["เค้ก", "khéek", "cake", "noun", "food"],
  ["ขนม", "khà-nǒm", "snack/dessert", "noun", "food"],
  ["ส้ม", "sôm", "orange", "noun", "food"],
  ["แอปเปิ้ล", "áep-pôen", "apple", "noun", "food"],
  ["กล้วย", "klûay", "banana", "noun", "food"],
  ["มะม่วง", "má-mûang", "mango", "noun", "food"],
  ["มะละกอ", "má-lá-koo", "papaya", "noun", "food"],
  ["ทุเรียน", "thú-rian", "durian", "noun", "food"],
  ["บ้าน", "bâan", "house/home", "noun", "places"],
  ["ห้อง", "hông", "room", "noun", "places"],
  ["โรงเรียน", "roong-rian", "school", "noun", "places"],
  ["มหาวิทยาลัย", "má-hǎa-wít-thá-yaa-lai", "university", "noun", "places"],
  ["โรงพยาบาล", "roong-phá-yaa-baan", "hospital", "noun", "places"],
  ["ร้านอาหาร", "ráan-aa-hǎan", "restaurant", "noun", "places"],
  ["ตลาด", "tà-làat", "market", "noun", "places"],
  ["ห้างสรรพสินค้า", "hâang-sàp-phá-sǐn-kháa", "department store", "noun", "places"],
  ["ธนาคาร", "thá-naa-khaan", "bank", "noun", "places"],
  ["สนามบิน", "sà-nǎam-bin", "airport", "noun", "places"],
  ["สถานีรถไฟ", "sà-thǎa-nii-rót-fai", "train station", "noun", "places"],
  ["วัด", "wát", "temple", "noun", "places"],
  ["โบสถ์", "bòot", "church", "noun", "places"],
  ["โรงแรม", "roong-raem", "hotel", "noun", "places"],
  ["ถนน", "thà-nǒn", "road/street", "noun", "places"],
  ["เมือง", "muueang", "city/town", "noun", "places"],
  ["หมู่บ้าน", "mùu-bâan", "village", "noun", "places"],
  ["ประเทศ", "prà-thêet", "country", "noun", "places"],
  ["ทะเล", "thá-lee", "sea/ocean", "noun", "places"],
  ["แม่น้ำ", "mâe-náam", "river", "noun", "places"],
  ["ภูเขา", "phuu-khǎo", "mountain", "noun", "places"],
  ["ป่า", "pàa", "forest/jungle", "noun", "places"],
  ["สวน", "sǔan", "garden/park", "noun", "places"],
  ["เวลา", "wee-laa", "time", "noun", "time"],
  ["วัน", "wan", "day", "noun", "time"],
  ["คืน", "khuuen", "night", "noun", "time"],
  ["สัปดาห์", "sàp-daa", "week", "noun", "time"],
  ["เดือน", "duuean", "month", "noun", "time"],
  ["ปี", "pii", "year", "noun", "time"],
  ["วันนี้", "wan-níi", "today", "noun", "time"],
  ["พรุ่งนี้", "phrûng-níi", "tomorrow", "noun", "time"],
  ["เมื่อวาน", "mûea-waan", "yesterday", "noun", "time"],
  ["ตอนนี้", "toon-níi", "now", "adverb", "time"],
  ["แล้ว", "láeo", "already/then", "adverb", "time"],
  ["เดี๋ยว", "dǐao", "soon/just a moment", "adverb", "time"],
  ["บ่อย", "bòi", "often", "adverb", "time"],
  ["นานๆ", "naan-naan", "rarely/occasionally", "adverb", "time"],
  ["เร็วๆ", "reo-reo", "soon", "adverb", "time"],
  ["เช้า", "cháo", "morning", "noun", "time"],
  ["กลางวัน", "klaang-wan", "noon/daytime", "noun", "time"],
  ["กลางคืน", "klaang-khuuen", "midnight/nighttime", "noun", "time"],
  ["วันจันทร์", "wan-jan", "Monday", "noun", "time"],
  ["วันอังคาร", "wan-ang-khaan", "Tuesday", "noun", "time"],
  ["วันพุธ", "wan-phút", "Wednesday", "noun", "time"],
  ["วันพฤหัสบดี", "wan-phá-rúe-hàt-sà-boo-dii", "Thursday", "noun", "time"],
  ["วันศุกร์", "wan-sùk", "Friday", "noun", "time"],
  ["วันเสาร์", "wan-sǎo", "Saturday", "noun", "time"],
  ["วันอาทิตย์", "wan-aa-thít", "Sunday", "noun", "time"],
  ["คน", "khon", "person/people", "noun", "general"],
  ["ผู้ชาย", "phûu-chaai", "man", "noun", "general"],
  ["ผู้หญิง", "phûu-yǐng", "woman", "noun", "general"],
  ["เด็ก", "dèk", "child", "noun", "general"],
  ["เพื่อน", "phûuean", "friend", "noun", "general"],
  ["ครู", "khruu", "teacher", "noun", "general"],
  ["หมอ", "mǒo", "doctor", "noun", "general"],
  ["ตำรวจ", "tam-rùat", "police", "noun", "general"],
  ["ทหาร", "thá-hǎan", "soldier", "noun", "general"],
  ["นักเรียน", "nák-rian", "student", "noun", "general"],
  ["นักธุรกิจ", "nák-thú-rá-kìt", "businessman", "noun", "general"],
  ["สัตว์", "sàt", "animal", "noun", "general"],
  ["หมา", "mǎa", "dog", "noun", "general"],
  ["แมว", "maeo", "cat", "noun", "general"],
  ["นก", "nók", "bird", "noun", "general"],
  ["ช้าง", "cháang", "elephant", "noun", "general"],
  ["รถ", "rót", "car/vehicle", "noun", "general"],
  ["รถยนต์", "rót-yon", "car (formal)", "noun", "general"],
  ["รถจักรยานยนต์", "rót-jàk-krá-yaan-yon", "motorcycle", "noun", "general"],
  ["รถไฟ", "rót-fai", "train", "noun", "general"],
  ["เครื่องบิน", "khrûueang-bin", "airplane", "noun", "general"],
  ["เรือ", "ruuea", "boat/ship", "noun", "general"],
  ["เงิน", "ngoen", "money", "noun", "general"],
  ["ราคา", "raa-khaa", "price", "noun", "general"],
  ["สินค้า", "sǐn-kháa", "goods/product", "noun", "general"],
  ["งาน", "ngaan", "work/job/event", "noun", "general"],
  ["บริษัท", "boo-rí-sàt", "company", "noun", "general"],
  ["โทรศัพท์", "thoo-rá-sàp", "phone", "noun", "general"],
  ["คอมพิวเตอร์", "khoom-phiu-tôoe", "computer", "noun", "general"],
  ["อินเทอร์เน็ต", "in-thooe-nét", "internet", "noun", "general"],
  ["ภาษา", "phaa-sǎa", "language", "noun", "general"],
  ["ภาษาไทย", "phaa-sǎa-thai", "Thai language", "noun", "general"],
  ["ภาษาอังกฤษ", "phaa-sǎa-ang-krìt", "English language", "noun", "general"],
  ["หนังสือ", "nǎng-sǔue", "book", "noun", "general"],
  ["หนังสือพิมพ์", "nǎng-sǔue-phim", "newspaper", "noun", "general"],
  ["จดหมาย", "jòt-mǎai", "letter/mail", "noun", "general"],
  ["ครับ", "khráp", "polite particle (male)", "particle", "particles"],
  ["ค่ะ", "khâ", "polite particle (female)", "particle", "particles"],
  ["นะ", "ná", "softening particle", "particle", "particles"],
  ["ล่ะ", "lâ", "question/emphasis particle", "particle", "particles"],
  ["สิ", "sì", "emphasis particle", "particle", "particles"],
  ["เถอะ", "thòe", "let's/please particle", "particle", "particles"],
  ["หน่อย", "nòi", "a little/please (soften)", "particle", "particles"],
  ["มาก", "mâak", "very/much/many", "adverb", "particles"],
  ["มากมาย", "mâak-maai", "a lot/plenty", "adverb", "particles"],
  ["น้อย", "nóoi", "little/few", "adverb", "particles"],
  ["นิดหน่อย", "nít-nòi", "a little bit", "adverb", "particles"],
  ["และ", "láe", "and", "conjunction", "connectors"],
  ["หรือ", "rǔue", "or", "conjunction", "connectors"],
  ["แต่", "tàe", "but", "conjunction", "connectors"],
  ["เพราะ", "phró", "because", "conjunction", "connectors"],
  ["ถ้า", "thâa", "if", "conjunction", "connectors"],
  ["เมื่อ", "mûea", "when (past)", "conjunction", "connectors"],
  ["ตอนที่", "toon-thîi", "when (at the time)", "conjunction", "connectors"],
  ["ก่อน", "kòon", "before", "preposition", "connectors"],
  ["ใน", "nai", "in/inside", "preposition", "connectors"],
  ["นอก", "nôok", "outside", "preposition", "connectors"],
  ["บน", "bon", "on/above", "preposition", "connectors"],
  ["ใต้", "tâi", "under/below", "preposition", "connectors"],
  ["ข้างๆ", "khâang-khâang", "beside/next to", "preposition", "connectors"],
  ["ระหว่าง", "rá-wàang", "between/during", "preposition", "connectors"],
  ["ที่", "thîi", "at/which/that", "preposition", "connectors"],
  ["จาก", "jàak", "from", "preposition", "connectors"],
  ["ถึง", "thǔeng", "to/until/arrive at", "preposition", "connectors"],
  ["กับ", "kàp", "with", "preposition", "connectors"],
  ["โดย", "dooi", "by/via", "preposition", "connectors"],
  ["เพื่อ", "phûuea", "for/in order to", "preposition", "connectors"],
  ["เกี่ยวกับ", "kìao-kàp", "about/regarding", "preposition", "connectors"],
  ["ไม่", "mâi", "no/not", "negation", "grammar"],
  ["ไม่ใช่", "mâi-châi", "is not/no (that's wrong)", "negation", "grammar"],
  ["ใช่", "châi", "yes (that's right)", "affirmative", "grammar"],
  ["ไม่เป็นไร", "mâi-pen-rai", "never mind/you're welcome", "phrase", "grammar"],
  ["เป็นไร", "pen-rai", "what's wrong/what is it", "phrase", "grammar"],
  ["สวัสดี", "sà-wàt-dii", "hello/goodbye", "phrase", "phrases"],
  ["ขอบคุณ", "khòop-khun", "thank you", "phrase", "phrases"],
  ["ขอโทษ", "khǒo-thôot", "sorry/excuse me", "phrase", "phrases"],
  ["ยินดีที่ได้รู้จัก", "yin-dii-thîi-dâi-rúu-jàk", "nice to meet you", "phrase", "phrases"],
  ["แล้วเจอกัน", "láeo-jooe-kan", "see you later", "phrase", "phrases"],
  ["ได้เลย", "dâi-looei", "sure/go ahead", "phrase", "phrases"],
  ["โอเค", "oo-khee", "okay", "phrase", "phrases"],
  ["ขอ...", "khǒo...", "please may I have...", "phrase", "phrases"],
  ["ช่วยได้ไหม", "chûay-dâi-mǎi", "can you help?", "phrase", "phrases"],
  ["สีแดง", "sǐi-daeng", "red", "noun", "colors"],
  ["สีส้ม", "sǐi-sôm", "orange", "noun", "colors"],
  ["สีเหลือง", "sǐi-lǔueang", "yellow", "noun", "colors"],
  ["สีเขียว", "sǐi-khǐao", "green", "noun", "colors"],
  ["สีฟ้า", "sǐi-fáa", "light blue/sky blue", "noun", "colors"],
  ["สีน้ำเงิน", "sǐi-náam-ngoen", "dark blue/navy", "noun", "colors"],
  ["สีม่วง", "sǐi-mûang", "purple", "noun", "colors"],
  ["สีชมพู", "sǐi-chom-phuu", "pink", "noun", "colors"],
  ["สีน้ำตาล", "sǐi-náam-taan", "brown", "noun", "colors"],
  ["สีดำ", "sǐi-dam", "black", "noun", "colors"],
  ["สีขาว", "sǐi-khǎao", "white", "noun", "colors"],
  ["สีเทา", "sǐi-thao", "gray", "noun", "colors"],
  ["ดวงอาทิตย์", "duuang-aa-thít", "sun", "noun", "nature"],
  ["ดวงจันทร์", "duuang-jan", "moon", "noun", "nature"],
  ["ดาว", "daao", "star", "noun", "nature"],
  ["ท้องฟ้า", "thóong-fáa", "sky", "noun", "nature"],
  ["เมฆ", "mêek", "cloud", "noun", "nature"],
  ["ฝน", "fǒn", "rain", "noun", "nature"],
  ["ลม", "lom", "wind", "noun", "nature"],
  ["พายุ", "phaa-yú", "storm", "noun", "nature"],
  ["น้ำท่วม", "náam-thûam", "flood", "noun", "nature"],
  ["หิมะ", "hì-má", "snow", "noun", "nature"],
  ["ดิน", "din", "earth/soil", "noun", "nature"],
  ["หิน", "hǐn", "stone/rock", "noun", "nature"],
  ["ต้นไม้", "tôn-máai", "tree", "noun", "nature"],
  ["ดอกไม้", "dòok-máai", "flower", "noun", "nature"],
  ["หญ้า", "yâa", "grass", "noun", "nature"],
  ["สุขภาพ", "sùk-khà-phâap", "health", "noun", "health"],
  ["โรค", "rôok", "disease/illness", "noun", "health"],
  ["ยา", "yaa", "medicine/drug", "noun", "health"],
  ["พยาบาล", "phá-yaa-baan", "nurse", "noun", "health"],
  ["อาการ", "aa-kaan", "symptom/condition", "noun", "health"],
  ["ไข้", "khâi", "fever", "noun", "health"],
  ["ไอ", "ai", "cough", "noun", "health"],
  ["เป็นหวัด", "pen-wàt", "to have a cold", "verb", "health"],
  ["ปวดหัว", "pùuat-hǔa", "headache", "noun", "health"],
  ["ปวดท้อง", "pùuat-thóong", "stomachache", "noun", "health"],
  ["การศึกษา", "kaan-sùek-sǎa", "education", "noun", "education"],
  ["สอบ", "sòop", "exam/to take a test", "noun", "education"],
  ["ผ่าน", "phàan", "to pass", "verb", "education"],
  ["สอบตก", "sòop-tòk", "to fail an exam", "verb", "education"],
  ["เกรด", "krèet", "grade", "noun", "education"],
  ["ชั้นเรียน", "chán-rian", "classroom", "noun", "education"],
  ["กระดาน", "krà-daan", "board/blackboard", "noun", "education"],
  ["ปากกา", "pàak-kaa", "pen", "noun", "education"],
  ["ดินสอ", "din-sǒo", "pencil", "noun", "education"],
  ["สมุด", "sà-mùt", "notebook", "noun", "education"],
  ["อาชีพ", "aa-chîip", "occupation/career", "noun", "work"],
  ["เงินเดือน", "ngoen-duuean", "salary/monthly wage", "noun", "work"],
  ["ค่าจ้าง", "khâa-jâang", "wages", "noun", "work"],
  ["สำนักงาน", "sǎm-nák-ngaan", "office", "noun", "work"],
  ["ประชุม", "prà-chum", "meeting/to meet", "noun", "work"],
  ["โปรเจกต์", "proo-jèkt", "project", "noun", "work"],
  ["ลูกค้า", "lûuk-kháa", "customer/client", "noun", "work"],
  ["ผู้จัดการ", "phûu-jàt-kaan", "manager", "noun", "work"],
  ["เพื่อนร่วมงาน", "phûuean-rûuam-ngaan", "colleague", "noun", "work"],
  ["เทคโนโลยี", "thék-noo-loo-yii", "technology", "noun", "tech"],
  ["แอป", "áep", "app", "noun", "tech"],
  ["เว็บไซต์", "wép-sâit", "website", "noun", "tech"],
  ["อีเมล", "ii-meo", "email", "noun", "tech"],
  ["รหัสผ่าน", "rá-hàt-phàan", "password", "noun", "tech"],
  ["ไฟล์", "fai", "file", "noun", "tech"],
  ["ดาวน์โหลด", "daaon-lôot", "download", "verb", "tech"],
  ["อัปโหลด", "àp-lôot", "upload", "verb", "tech"],
  ["ทั้งหมด", "tháng-mòt", "all/everything", "determiner", "general"],
  ["บางส่วน", "baang-sùuan", "some/part of", "determiner", "general"],
  ["หลาย", "lǎai", "many/several", "determiner", "general"],
  ["ทุก", "thúk", "every/all", "determiner", "general"],
  ["แต่ละ", "tàe-lá", "each", "determiner", "general"],
  ["อื่น", "ùuen", "other", "determiner", "general"],
  ["เดียวกัน", "diao-kan", "same", "adjective", "general"],
  ["ต่างกัน", "tàang-kan", "different", "adjective", "general"],
  ["เหมือนกัน", "mǔuean-kan", "similar/same (informal)", "adjective", "general"],
  ["ประมาณ", "prà-maan", "approximately/about", "adverb", "general"],
  ["แน่นอน", "nâe-noon", "certainly/of course", "adverb", "general"],
  ["บางที", "baang-thii", "sometimes/maybe", "adverb", "general"],
  ["ปกติ", "pà-kà-tì", "normally/usually", "adverb", "general"],
  ["ทันที", "than-thii", "immediately", "adverb", "general"],
  ["ด้วย", "dûay", "also/too/with", "adverb", "general"],
  ["แค่", "khâe", "just/only", "adverb", "general"],
  ["เพียง", "phiang", "only/merely", "adverb", "general"],
  ["จริงๆ", "jing-jing", "really/truly", "adverb", "general"],
  ["เกินไป", "kooen-pai", "too much/excessively", "adverb", "general"],
  ["พอ", "phoo", "enough", "adverb", "general"],
  ["ไม่พอ", "mâi-phoo", "not enough", "adverb", "general"],
  ["สำเร็จ", "sǎm-rèt", "success/to succeed", "verb", "verbs_core"],
  ["ล้มเหลว", "lóm-lǎo", "to fail", "verb", "verbs_core"],
  ["พยายาม", "phá-yaa-yaam", "to try/attempt", "verb", "verbs_core"],
  ["ยอม", "yoom", "to give in/accept", "verb", "verbs_core"],
  ["ปฏิเสธ", "pà-tì-sèet", "to refuse/deny", "verb", "verbs_core"],
  ["เชื่อ", "chûuea", "to believe/trust", "verb", "verbs_core"],
  ["สงสัย", "sǒng-sǎi", "to doubt/be curious", "verb", "verbs_core"],
  ["ตัดสินใจ", "tàt-sǐn-jai", "to decide", "verb", "verbs_core"],
  ["เลือก", "lûueak", "to choose/select", "verb", "verbs_core"],
  ["แนะนำ", "náe-nam", "to recommend/introduce", "verb", "verbs_core"],
  ["อธิบาย", "à-thì-baai", "to explain", "verb", "verbs_core"],
  ["ยืนยัน", "yuuen-yan", "to confirm", "verb", "verbs_core"],
  ["ตรวจสอบ", "trùuat-sòop", "to check/verify", "verb", "verbs_core"],
  ["แก้ไข", "kâe-khǎi", "to fix/correct", "verb", "verbs_core"],
  ["สร้าง", "sâang", "to build/create", "verb", "verbs_core"],
  ["ทำลาย", "tham-laai", "to destroy", "verb", "verbs_core"],
  ["ส่ง", "sòng", "to send", "verb", "verbs_core"],
  ["รับส่ง", "ráp-sòng", "to pick up and drop off", "verb", "verbs_core"],
  ["โทร", "thoo", "to call (phone)", "verb", "verbs_core"],
  ["เดินทาง", "dooen-thaang", "to travel", "verb", "verbs_core"],
  ["ท่องเที่ยว", "thông-thîao", "to tour/sightsee", "verb", "verbs_core"],
  ["จอง", "joong", "to book/reserve", "verb", "verbs_core"],
  ["เช็คอิน", "chék-in", "to check in", "verb", "verbs_core"],
  ["ชำระเงิน", "cham-rá-ngoen", "to pay", "verb", "verbs_core"],
  ["คืนเงิน", "khuuen-ngoen", "to refund", "verb", "verbs_core"],
  ["ต่อรอง", "tòo-roong", "to negotiate/bargain", "verb", "verbs_core"],
  ["ฉลอง", "chà-loong", "to celebrate", "verb", "verbs_core"],
  ["เชิญ", "chooen", "to invite", "verb", "verbs_core"],
  ["แต่งงาน", "tàeng-ngaan", "to marry/get married", "verb", "verbs_core"],
  ["หย่า", "yàa", "to divorce", "verb", "verbs_core"],
  ["ให้อภัย", "hâi-à-phai", "to forgive", "verb", "verbs_core"],
  ["ต้อนรับ", "tôon-ráp", "to welcome", "verb", "verbs_core"],
  ["ปฏิบัติ", "pà-tì-bàt", "to practice/treat", "verb", "verbs_core"],
  ["ฝึก", "fùek", "to train/practice", "verb", "verbs_core"],
  ["ออกกำลังกาย", "òok-kam-lang-kaai", "to exercise", "verb", "verbs_core"],
  ["นับ", "náp", "to count", "verb", "verbs_core"],
  ["คำนวณ", "kham-nuuan", "to calculate", "verb", "verbs_core"],
  ["เปรียบเทียบ", "prìap-thîap", "to compare", "verb", "verbs_core"],
  ["แบ่ง", "bàeng", "to divide/share", "verb", "verbs_core"],
  ["รวม", "ruuam", "to combine/include", "verb", "verbs_core"],
  ["แยก", "yâek", "to separate", "verb", "verbs_core"],
  ["หยุด", "yùt", "to stop", "verb", "verbs_core"],
  ["เริ่มต้น", "rôoem-tôn", "to begin", "verb", "verbs_core"],
  ["ดำเนิน", "dam-nooein", "to proceed/carry out", "verb", "verbs_core"],
  ["ควบคุม", "khûuap-khum", "to control", "verb", "verbs_core"],
  ["จัดการ", "jàt-kaan", "to manage/arrange", "verb", "verbs_core"],
  ["เตรียม", "triam", "to prepare", "verb", "verbs_core"],
  ["ซ่อม", "sôom", "to repair/fix", "verb", "verbs_core"],
  ["สร้างสรรค์", "sâang-sǎn", "to be creative", "verb", "verbs_core"],
  ["เพิ่ม", "phôoem", "to add/increase", "verb", "verbs_core"],
  ["ลด", "lót", "to reduce/decrease", "verb", "verbs_core"],
  ["ขยาย", "khà-yǎai", "to expand", "verb", "verbs_core"],
  ["ย่อ", "yôo", "to shrink/abbreviate", "verb", "verbs_core"],
  ["ปรับปรุง", "pràp-prung", "to improve", "verb", "verbs_core"],
  ["พัฒนา", "phát-thá-naa", "to develop", "verb", "verbs_core"],
  ["เปิดตัว", "pòoet-tua", "to launch/introduce", "verb", "verbs_core"],
  ["สั่ง", "sàng", "to order/command", "verb", "verbs_core"],
  ["ตาม", "taam", "to follow/according to", "verb", "verbs_core"],
  ["นำ", "nam", "to lead/bring", "verb", "verbs_core"],
  ["พา", "phaa", "to take/bring (person)", "verb", "verbs_core"],
  ["ติดตาม", "tìt-taam", "to follow/track", "verb", "verbs_core"],
  ["ตามหา", "taam-hǎa", "to search for", "verb", "verbs_core"],
  ["พบ", "phóp", "to meet/find", "verb", "verbs_core"],
  ["เจอ", "jooe", "to meet/encounter", "verb", "verbs_core"],
  ["รู้สึก", "rúu-sùek", "to feel", "verb", "verbs_core"],
  ["เป็นห่วง", "pen-hùuang", "to worry about", "verb", "verbs_core"],
  ["ดีใจ", "dii-jai", "to be glad/happy", "verb", "verbs_core"],
  ["เสียใจ", "sǐa-jai", "to be sad/sorry", "verb", "verbs_core"],
  ["ตกใจ", "tòk-jai", "to be startled/shocked", "verb", "verbs_core"],
  ["แปลกใจ", "plàek-jai", "to be surprised", "verb", "verbs_core"],
  ["สนใจ", "sǒn-jai", "to be interested in", "verb", "verbs_core"],
  ["เบื่อ", "bùuea", "to be bored", "verb", "verbs_core"],
  ["เพลิดเพลิน", "phloet-phloen", "to enjoy/have fun", "verb", "verbs_core"],
  ["หัวเราะ", "hǔa-ró", "to laugh", "verb", "verbs_core"],
  ["ร้องไห้", "róong-hâi", "to cry", "verb", "verbs_core"],
  ["ยิ้ม", "yím", "to smile", "verb", "verbs_core"],
  ["ถอนหายใจ", "thǒon-hǎai-jai", "to sigh", "verb", "verbs_core"],
  ["ขนาด", "khà-nàat", "size", "noun", "general"],
  ["รูปร่าง", "rûup-râang", "shape/figure", "noun", "general"],
  ["สี", "sǐi", "color", "noun", "general"],
  ["น้ำหนัก", "náam-nàk", "weight", "noun", "general"],
  ["ความสูง", "khwaam-sǔung", "height", "noun", "general"],
  ["ระยะทาง", "rá-yá-thaang", "distance", "noun", "general"],
  ["ความเร็ว", "khwaam-reo", "speed", "noun", "general"],
  ["อุณหภูมิ", "un-hà-phuum", "temperature", "noun", "general"],
  ["แสงสว่าง", "sǎeng-sà-wàang", "light/brightness", "noun", "general"],
  ["เงาะ", "ngó", "darkness/shadow", "noun", "general"],
  ["เสียง", "sǐang", "sound/voice", "noun", "general"],
  ["กลิ่น", "klìn", "smell/scent", "noun", "general"],
  ["รส", "rót", "taste/flavor", "noun", "general"],
  ["สัมผัส", "sǎm-phàt", "touch/feel", "noun", "general"],
  ["ประสบการณ์", "prà-sòp-kaan", "experience", "noun", "general"],
  ["ความรู้", "khwaam-rúu", "knowledge", "noun", "general"],
  ["ความคิด", "khwaam-khít", "thought/idea", "noun", "general"],
  ["ความฝัน", "khwaam-fǎn", "dream", "noun", "general"],
  ["ความจริง", "khwaam-jing", "truth/reality", "noun", "general"],
  ["ปัญหา", "pan-hǎa", "problem", "noun", "general"],
  ["วิธี", "wí-thii", "method/way", "noun", "general"],
  ["เหตุผล", "hèet-phǒn", "reason", "noun", "general"],
  ["ผล", "phǒn", "result/fruit", "noun", "general"],
  ["ความสำเร็จ", "khwaam-sǎm-rèt", "success", "noun", "general"],
  ["ความล้มเหลว", "khwaam-lóm-lǎo", "failure", "noun", "general"],
  ["โอกาส", "oo-kàat", "opportunity/chance", "noun", "general"],
  ["ความเสี่ยง", "khwaam-sìiang", "risk", "noun", "general"],
  ["ข้อมูล", "khôo-muun", "information/data", "noun", "general"],
  ["ข่าว", "khàao", "news", "noun", "general"],
  ["เรื่อง", "rûueang", "story/matter/about", "noun", "general"],
  ["ตัวอย่าง", "tua-yàang", "example", "noun", "general"],
  ["ประเภท", "prà-phêet", "type/category", "noun", "general"],
  ["ส่วน", "sùuan", "part/section", "noun", "general"],
  ["ระดับ", "rá-dàp", "level", "noun", "general"],
  ["จำนวน", "jam-nuuan", "amount/number", "noun", "general"],
  ["ปริมาณ", "prì-maan", "quantity", "noun", "general"],
  ["คุณภาพ", "khun-ná-phâap", "quality", "noun", "general"],
  ["ค่า", "khâa", "value/fee/worth", "noun", "general"],
  ["กฎ", "kòt", "rule/law", "noun", "general"],
  ["สิทธิ์", "sìt", "right/permission", "noun", "general"],
  ["หน้าที่", "nâa-thîi", "duty/function", "noun", "general"],
  ["ความรับผิดชอบ", "khwaam-ráp-phìt-chôop", "responsibility", "noun", "general"],
  ["คำ", "kham", "word", "noun", "general"],
  ["ประโยค", "prà-yòok", "sentence", "noun", "general"],
  ["คำถาม", "kham-thǎam", "question", "noun", "general"],
  ["คำตอบ", "kham-tòop", "answer", "noun", "general"],
  ["ชื่อ", "chûue", "name", "noun", "general"],
  ["นามสกุล", "naam-sà-kun", "surname/last name", "noun", "general"],
  ["อายุ", "aa-yú", "age", "noun", "general"],
  ["เพศ", "phêet", "gender/sex", "noun", "general"],
  ["สัญชาติ", "sǎn-châat", "nationality", "noun", "general"],
  ["ศาสนา", "sǎat-sà-nǎa", "religion", "noun", "general"],
  ["สำหรับ", "sǎm-ràp", "for/for the purpose of", "preposition", "connectors"],
  ["ตัว", "tua", "body/self/classifier (animals & objects)", "noun", "general"],
  ["ตก", "tòk", "to fall/to drop", "verb", "verbs_core"],
  ["ใส่", "sài", "to put in/to wear/to add", "verb", "verbs_core"],
  ["ออก", "òok", "out/to exit/to go out", "verb", "verbs_core"],
  ["สด", "sòt", "fresh/raw/live", "adjective", "adjectives"],
  ["ความ", "khwaam", "abstract noun prefix (quality/state)", "noun", "general"],
  ["กรุณา", "ka-rú-naa", "please/kindly", "adverb", "adverbs"],
  ["ขับ", "khàp", "to drive", "verb", "verbs_core"],
  ["อีก", "ìik", "more/again/another", "adverb", "adverbs"],
  ["ทั้ง", "tháng", "all/both/entirely", "determiner", "general"],
  ["หลับ", "làp", "to sleep/asleep", "verb", "verbs_core"],
  ["เยอะ", "yóe", "a lot/many (informal)", "adverb", "adverbs"],
  ["จาน", "jaan", "plate/dish", "noun", "food"],
  ["หอม", "hǒom", "fragrant/aromatic", "adjective", "adjectives"],
  ["นุ่ม", "nûm", "soft/tender", "adjective", "adjectives"],
  ["ดึก", "dùek", "late at night", "adverb", "adverbs"],
  ["สุด", "sùt", "most/extreme/end", "adverb", "adverbs"],
  ["มะนาว", "má-naao", "lime/lemon", "noun", "food"],
  ["เหลือ", "lǔuea", "remaining/left over", "verb", "verbs_core"],
  ["ญี่ปุ่น", "yîi-pùn", "Japan/Japanese", "noun", "general"],
  ["ชนิด", "chá-nít", "type/kind/variety", "noun", "general"],
  ["นัก", "nák", "very/-er (intensifier suffix)", "adverb", "adverbs"],
  ["คัน", "khan", "classifier for vehicles", "noun", "general"],
  ["ข้าง", "khâang", "side/beside/next to", "noun", "general"],
  ["งาม", "ngaam", "beautiful/elegant (formal)", "adjective", "adjectives"],
  ["ผู้", "phûu", "person who/the one who (prefix)", "noun", "general"],
  ["สาย", "sǎai", "late/line/strand", "adjective", "adjectives"],
  ["ตั้ง", "tâng", "to set up/since/as many as", "verb", "verbs_core"],
  ["ต่าง", "tàang", "different/foreign/various", "adjective", "adjectives"],
  ["น่า", "nâa", "worth-/ought to/-able (prefix)", "adverb", "adverbs"],
  ["ดัง", "dang", "famous/well-known/loud", "adjective", "adjectives"],
  ["คณิตศาสตร์", "khá-nít-tà-sàat", "mathematics", "noun", "education"],
  ["ปาร์ตี้", "pàat-tîi", "party (social)", "noun", "general"],
  ["ตรง", "trong", "straight/direct/exactly", "adjective", "adjectives"],
  ["ป้าย", "pâai", "sign/label/bus stop", "noun", "general"],
  ["อำเภอ", "am-phoe", "district (administrative)", "noun", "general"],
  ["ใจ", "jai", "heart/mind/spirit", "noun", "general"],
  ["นัด", "nát", "appointment/to arrange to meet", "noun", "general"],
  ["คะ", "khâ", "polite particle (female, statement)", "particle", "particles"],
  ["บ่าย", "bàai", "afternoon (noon–4 pm)", "noun", "general"],
  ["หนัง", "nǎng", "film/movie/leather", "noun", "general"],
  ["สถานี", "sà-thǎa-nii", "station (bus/train/police)", "noun", "general"],
  ["เธอ", "thoe", "she/her/you (informal female)", "pronoun", "pronouns"],
  ["ไหม", "mǎi", "question particle (yes/no)", "particle", "particles"],
  ["กัน", "kan", "together/each other (reciprocal)", "particle", "particles"],
  ["ไทย", "thai", "Thai (person/language/country)", "adjective", "adjectives"],
  ["นี่", "nîi", "this/here (informal)", "demonstrative", "pronouns"],
  ["ร้าน", "ráan", "shop/restaurant/stall", "noun", "general"],
  ["ขอ", "khǒo", "to request/may I", "verb", "verbs_core"],
  ["เลย", "looei", "at all/so/just/right away", "adverb", "adverbs"],
  ["ตอน", "toon", "period/when/episode", "noun", "general"],
  ["โมง", "moong", "o'clock (daytime hours)", "noun", "general"],
  ["กว่า", "kwàa", "more than/than/over", "adverb", "adverbs"],
  ["ว่า", "wâa", "that (conjunction)/to say", "conjunction", "connectors"],
  ["ขึ้น", "khûen", "up/to rise/to go up", "verb", "verbs_core"],
  ["คือ", "khuue", "is/namely/that is", "verb", "verbs_core"],
  ["ทาง", "thaang", "way/path/direction/via", "noun", "general"],
  ["แก้ว", "kâeo", "glass (drinking)/cup", "noun", "general"],
  ["ต่อ", "tòo", "per/per unit/next/to connect", "adverb", "adverbs"],
  ["บาท", "bàat", "baht (Thai currency)", "noun", "general"],
  ["อากาศ", "aa-kàat", "weather/air/climate", "noun", "general"],
  ["สนุก", "sà-nùk", "fun/enjoyable/entertaining", "adjective", "adjectives"],
  ["กระเป๋า", "krà-pǎo", "bag/purse/wallet", "noun", "general"],
  ["ใกล้", "klâi", "near/close", "adjective", "adjectives"],
  ["เสื้อ", "sûuea", "shirt/top/garment", "noun", "general"],
  ["ชั่วโมง", "chûua-moong", "hour", "noun", "general"],
  ["เก่ง", "kèng", "skilled/good at/talented", "adjective", "adjectives"],
  ["ก็", "kôo", "also / then (particle)", "particle", "particles"],
  ["ของ", "khǒong", "of / belonging to", "preposition", "connectors"],
  ["การ", "kaan", "the act of (nominaliser)", "noun", "grammar"],
  ["ชีวิต", "chii-wít", "life", "noun", "general"],
  ["เมนู", "mee-nuu", "menu", "noun", "restaurant"],
  ["รายการอาหาร", "raai-kaan-aa-hǎan", "food list / menu", "noun", "restaurant"],
  ["อาหารจานหลัก", "aa-hǎan-jaan-làk", "main course", "noun", "restaurant"],
  ["อาหารเรียกน้ำย่อย", "aa-hǎan-rîak-náam-yôi", "appetiser", "noun", "restaurant"],
  ["ของหวาน", "khǒong-wǎan", "dessert", "noun", "restaurant"],
  ["เครื่องดื่ม", "khrûueang-dùuem", "drink / beverage", "noun", "restaurant"],
  ["สั่งอาหาร", "sàng-aa-hǎan", "to order food", "verb", "restaurant"],
  ["เก็บเงิน", "kèp-ngoen", "to pay / get the bill", "verb", "restaurant"],
  ["บิล", "bin", "bill / check", "noun", "restaurant"],
  ["ใบเสร็จ", "bai-sèt", "receipt", "noun", "restaurant"],
  ["โต๊ะ", "tó", "table", "noun", "restaurant"],
  ["ที่นั่ง", "thîi-nâng", "seat", "noun", "restaurant"],
  ["พนักงานเสิร์ฟ", "phá-nák-ngaan-sôoef", "waiter / waitress", "noun", "restaurant"],
  ["เชฟ", "chéef", "chef", "noun", "restaurant"],
  ["ผัด", "phàt", "stir-fried", "verb", "restaurant"],
  ["ต้ม", "tôm", "boiled", "verb", "restaurant"],
  ["ทอด", "thôot", "deep-fried", "verb", "restaurant"],
  ["ย่าง", "yâang", "grilled / roasted", "verb", "restaurant"],
  ["นึ่ง", "nûeng", "steamed", "verb", "restaurant"],
  ["ดิบ", "dìp", "raw", "adjective", "restaurant"],
  ["สุก", "sùk", "cooked / ripe", "adjective", "restaurant"],
  ["เผ็ดน้อย", "phèt-nóoi", "a little spicy", "adjective", "restaurant"],
  ["เผ็ดมาก", "phèt-mâak", "very spicy", "adjective", "restaurant"],
  ["ไม่เผ็ด", "mâi-phèt", "not spicy", "adjective", "restaurant"],
  ["หวานน้อย", "wǎan-nóoi", "less sweet", "adjective", "restaurant"],
  ["ไม่ใส่ผงชูรส", "mâi-sài-phǒng-chuu-rót", "no MSG", "phrase", "restaurant"],
  ["มังสวิรัติ", "mang-sà-wí-rát", "vegetarian", "adjective", "restaurant"],
  ["วีแกน", "wii-kaen", "vegan", "adjective", "restaurant"],
  ["แพ้", "pháe", "allergic to", "verb", "restaurant"],
  ["แพ้ถั่ว", "pháe-thùa", "allergic to nuts", "phrase", "restaurant"],
  ["แพ้อาหารทะเล", "pháe-aa-hǎan-thá-lee", "allergic to seafood", "phrase", "restaurant"],
  ["ฮาลาล", "haa-laan", "halal", "adjective", "restaurant"],
  ["ข้าวผัด", "khâao-phàt", "fried rice", "noun", "restaurant"],
  ["ผัดไทย", "phàt-thai", "Pad Thai", "noun", "restaurant"],
  ["ต้มยำ", "tôm-yam", "Tom Yum soup", "noun", "restaurant"],
  ["ต้มข่า", "tôm-khàa", "coconut galangal soup", "noun", "restaurant"],
  ["แกงเขียวหวาน", "kaeng-khǐao-wǎan", "green curry", "noun", "restaurant"],
  ["แกงแดง", "kaeng-daeng", "red curry", "noun", "restaurant"],
  ["แกงมัสมั่น", "kaeng-mát-sà-màn", "Massaman curry", "noun", "restaurant"],
  ["ส้มตำ", "sôm-tam", "papaya salad", "noun", "restaurant"],
  ["ลาบ", "lâap", "Laab (minced meat salad)", "noun", "restaurant"],
  ["ยำ", "yam", "Thai salad / spicy salad", "noun", "restaurant"],
  ["ข้าวมันไก่", "khâao-man-kài", "Khao Man Gai (chicken rice)", "noun", "restaurant"],
  ["ข้าวหมูแดง", "khâao-mǔu-daeng", "red pork rice", "noun", "restaurant"],
  ["ราดหน้า", "râat-nâa", "noodles with gravy", "noun", "restaurant"],
  ["ก๋วยเตี๋ยว", "kǔuay-tǐao", "noodle soup", "noun", "restaurant"],
  ["ผัดซีอิ๊ว", "phàt-sii-íu", "stir-fried flat noodles", "noun", "restaurant"],
  ["ข้าวเหนียว", "khâao-nǐao", "sticky rice", "noun", "restaurant"],
  ["มะม่วงข้าวเหนียว", "má-mûang-khâao-nǐao", "mango sticky rice", "noun", "restaurant"],
  ["กะเพรา", "kà-phrao", "Thai basil (as in krapao)", "noun", "restaurant"],
  ["ข้าวกะเพรา", "khâao-kà-phrao", "basil stir-fry with rice", "noun", "restaurant"],
  ["หมูสับ", "mǔu-sàp", "minced pork", "noun", "restaurant"],
  ["หมูกรอบ", "mǔu-krôop", "crispy pork belly", "noun", "restaurant"],
  ["หมูย่าง", "mǔu-yâang", "grilled pork", "noun", "restaurant"],
  ["หมูทอด", "mǔu-thôot", "fried pork", "noun", "restaurant"],
  ["หมูแดดเดียว", "mǔu-dàet-diao", "sun-dried pork", "noun", "restaurant"],
  ["หมูสามชั้น", "mǔu-sǎam-chán", "pork belly (three layers)", "noun", "restaurant"],
  ["ซี่โครงหมู", "sîi-khrong-mǔu", "pork ribs", "noun", "restaurant"],
  ["ไส้กรอก", "sâi-krôok", "sausage", "noun", "restaurant"],
  ["หมูหัน", "mǔu-hǎn", "roast suckling pig", "noun", "restaurant"],
  ["เนื้อวัว", "núuea-wua", "beef", "noun", "restaurant"],
  ["เนื้อสันใน", "núuea-sǎn-nai", "tenderloin / fillet", "noun", "restaurant"],
  ["เนื้อสันนอก", "núuea-sǎn-nôok", "sirloin", "noun", "restaurant"],
  ["เนื้อย่าง", "núuea-yâang", "grilled beef", "noun", "restaurant"],
  ["สเต็ก", "sà-tèk", "steak", "noun", "restaurant"],
  ["เนื้อสุก", "núuea-sùk", "well-done beef", "noun", "restaurant"],
  ["เนื้อกึ่งสุกกึ่งดิบ", "núuea-kûeng-sùk-kûeng-dìp", "medium beef", "noun", "restaurant"],
  ["เนื้อดิบ", "núuea-dìp", "rare beef", "noun", "restaurant"],
  ["เนื้อตุ๋น", "núuea-tǔn", "braised / stewed beef", "noun", "restaurant"],
  ["เนื้อสับ", "núuea-sàp", "minced beef", "noun", "restaurant"],
  ["อกไก่", "òk-kài", "chicken breast", "noun", "restaurant"],
  ["น่องไก่", "nôong-kài", "chicken drumstick", "noun", "restaurant"],
  ["ปีกไก่", "pìik-kài", "chicken wing", "noun", "restaurant"],
  ["ไก่ย่าง", "kài-yâang", "grilled chicken", "noun", "restaurant"],
  ["ไก่ทอด", "kài-thôot", "fried chicken", "noun", "restaurant"],
  ["ไก่อบ", "kài-òp", "baked chicken", "noun", "restaurant"],
  ["ไก่ผัดเม็ดมะม่วง", "kài-phàt-mét-má-mûang", "chicken with cashew nuts", "noun", "restaurant"],
  ["อาหารทะเล", "aa-hǎan-thá-lee", "seafood", "noun", "restaurant"],
  ["กุ้ง", "kûng", "shrimp / prawn", "noun", "restaurant"],
  ["กุ้งแม่น้ำ", "kûng-mâe-náam", "river prawn", "noun", "restaurant"],
  ["ปู", "puu", "crab", "noun", "restaurant"],
  ["ปูผัดผงกะหรี่", "puu-phàt-phǒng-kà-rîi", "crab stir-fried with curry powder", "noun", "restaurant"],
  ["หอย", "hǒoi", "shellfish / mollusc", "noun", "restaurant"],
  ["หอยนางรม", "hǒoi-naang-rom", "oyster", "noun", "restaurant"],
  ["หอยแมลงภู่", "hǒoi-mà-laeng-phûu", "mussel", "noun", "restaurant"],
  ["หอยลาย", "hǒoi-laai", "clam", "noun", "restaurant"],
  ["ปลาหมึก", "plaa-mùek", "squid / cuttlefish", "noun", "restaurant"],
  ["ปลาหมึกย่าง", "plaa-mùek-yâang", "grilled squid", "noun", "restaurant"],
  ["ปลาทับทิม", "plaa-tháp-thim", "red tilapia", "noun", "restaurant"],
  ["ปลากะพง", "plaa-kà-phong", "sea bass / snapper", "noun", "restaurant"],
  ["ปลาทอด", "plaa-thôot", "fried fish", "noun", "restaurant"],
  ["ปลานึ่งมะนาว", "plaa-nûeng-má-naao", "steamed fish with lime", "noun", "restaurant"],
  ["ต้มยำกุ้ง", "tôm-yam-kûng", "Tom Yum prawn soup", "noun", "restaurant"],
  ["ผัดฉ่า", "phàt-chàa", "spicy stir-fried seafood", "noun", "restaurant"],
  ["น้ำเปล่า", "náam-plào", "plain water", "noun", "restaurant"],
  ["น้ำแข็ง", "náam-khǎeng", "ice", "noun", "restaurant"],
  ["ไม่ใส่น้ำแข็ง", "mâi-sài-náam-khǎeng", "no ice", "phrase", "restaurant"],
  ["ชาเย็น", "chaa-yen", "Thai iced tea", "noun", "restaurant"],
  ["กาแฟเย็น", "kaa-fae-yen", "iced coffee", "noun", "restaurant"],
  ["น้ำส้ม", "náam-sôm", "orange juice", "noun", "restaurant"],
  ["น้ำมะพร้าว", "náam-má-phráao", "coconut water", "noun", "restaurant"],
  ["โซดา", "soo-daa", "soda water", "noun", "restaurant"],
  ["ทางด่วน", "thaang-dùuan", "expressway / highway", "noun", "highway"],
  ["ทางหลวง", "thaang-lǔuang", "national highway", "noun", "highway"],
  ["ทางหลวงชนบท", "thaang-lǔuang-chon-ná-bòt", "rural road", "noun", "highway"],
  ["เส้นทาง", "sên-thaang", "route", "noun", "highway"],
  ["วงแหวน", "wong-wǎen", "ring road / beltway", "noun", "highway"],
  ["สะพาน", "sà-phaan", "bridge", "noun", "highway"],
  ["อุโมงค์", "ù-moong", "tunnel", "noun", "highway"],
  ["ทางออก", "thaang-òok", "exit", "noun", "highway"],
  ["ทางเข้า", "thaang-khâo", "entrance", "noun", "highway"],
  ["ทางแยก", "thaang-yâek", "junction / intersection", "noun", "highway"],
  ["วงเวียน", "wong-wian", "roundabout", "noun", "highway"],
  ["สี่แยก", "sìi-yâek", "four-way intersection", "noun", "highway"],
  ["ทางโค้ง", "thaang-khóong", "curve / bend in road", "noun", "highway"],
  ["เลน", "leen", "lane", "noun", "highway"],
  ["เลนซ้าย", "leen-sáai", "left lane", "noun", "highway"],
  ["เลนขวา", "leen-khwǎa", "right lane", "noun", "highway"],
  ["เลนฉุกเฉิน", "leen-chùk-chooen", "emergency lane", "noun", "highway"],
  ["ไหล่ทาง", "lài-thaang", "road shoulder", "noun", "highway"],
  ["เขตชุมชน", "khèet-chum-chon", "built-up area / urban zone", "noun", "highway"],
  ["ด่านเก็บเงิน", "dàan-kèp-ngoen", "toll plaza / toll booth", "noun", "highway"],
  ["ด่านทางด่วน", "dàan-thaang-dùuan", "expressway toll gate", "noun", "highway"],
  ["ค่าผ่านทาง", "khâa-phàan-thaang", "toll fee", "noun", "highway"],
  ["Easy Pass", "ii-sîi-pàat", "Easy Pass (electronic toll)", "noun", "highway"],
  ["M-Flow", "em-flow", "M-Flow (open-road tolling)", "noun", "highway"],
  ["ชะลอ", "chá-loo", "slow down", "verb", "highway"],
  ["ระวัง", "rá-wang", "caution / watch out", "verb", "highway"],
  ["ห้ามแซง", "hâam-saeng", "no overtaking", "phrase", "highway"],
  ["ห้ามจอด", "hâam-jòot", "no parking", "phrase", "highway"],
  ["ห้ามเข้า", "hâam-khâo", "no entry", "phrase", "highway"],
  ["ทางเดียว", "thaang-diao", "one way", "phrase", "highway"],
  ["ลดความเร็ว", "lót-khwaam-reo", "reduce speed", "phrase", "highway"],
  ["จำกัดความเร็ว", "jam-kàt-khwaam-reo", "speed limit", "noun", "highway"],
  ["กิโลเมตรต่อชั่วโมง", "ki-loo-meet-tòo-chûua-moong", "km/h", "noun", "highway"],
  ["กิโลเมตร", "ki-loo-meet", "kilometre", "noun", "highway"],
  ["ก่อสร้าง", "kòo-sâang", "construction / under construction", "noun", "highway"],
  ["งานก่อสร้าง", "ngaan-kòo-sâang", "construction work ahead", "noun", "highway"],
  ["ปิดเส้นทาง", "pìt-sên-thaang", "road closed", "phrase", "highway"],
  ["เบี่ยงเส้นทาง", "bìiang-sên-thaang", "detour / diversion", "phrase", "highway"],
  ["อุบัติเหตุ", "ù-bàt-tì-hèet", "accident", "noun", "highway"],
  ["รถเสีย", "rót-sǐa", "broken down vehicle", "noun", "highway"],
  ["รถติด", "rót-tìt", "traffic jam", "noun", "highway"],
  ["จราจร", "jà-raa-joon", "traffic", "noun", "highway"],
  ["ไฟจราจร", "fai-jà-raa-joon", "traffic light", "noun", "highway"],
  ["ปั๊มน้ำมัน", "pâm-náam-man", "petrol station / gas station", "noun", "highway"],
  ["บริการ", "boo-rí-kaan", "service area / services", "noun", "highway"],
  ["ที่พักริมทาง", "thîi-phák-rim-thaang", "roadside rest stop", "noun", "highway"],
  ["ตำรวจทางหลวง", "tam-rùat-thaang-lǔuang", "highway police", "noun", "highway"],
  ["เหนือ", "nǔuea", "north", "noun", "highway"],
  ["ตะวันออก", "tà-wan-òok", "east", "noun", "highway"],
  ["ตะวันตก", "tà-wan-tòk", "west", "noun", "highway"],
  ["กรุงเทพฯ", "krung-thêep", "Bangkok", "noun", "highway"],
  ["ศูนย์กลาง", "sǔun-klaang", "centre / central", "noun", "highway"],
  ["ชลบุรี", "chon-bú-rii", "Chonburi (province/city)", "noun", "highway"],
  ["พัทยา", "phát-thá-yaa", "Pattaya", "noun", "highway"],
  ["บางแสน", "baang-sǎen", "Bang Saen (beach town)", "noun", "highway"],
  ["ศรีราชา", "sǐi-raa-chaa", "Si Racha", "noun", "highway"],
  ["แหลมฉบัง", "lǎem-chà-bang", "Laem Chabang (port/industrial)", "noun", "highway"],
  ["บ้านบึง", "bâan-bueng", "Ban Bueng", "noun", "highway"],
  ["พนัสนิคม", "phá-nát-ní-khom", "Phanat Nikhom", "noun", "highway"],
  ["สัตหีบ", "sàt-tà-hîip", "Sattahip", "noun", "highway"],
  ["บางละมุง", "baang-lá-mung", "Bang Lamung (Pattaya district)", "noun", "highway"],
  ["เกาะสีชัง", "kò-sǐi-chang", "Ko Si Chang (island)", "noun", "highway"],
  ["นิคมอมตะนคร", "ní-khom-à-má-taa-ná-khoon", "Amata Nakhon industrial estate", "noun", "highway"],
  ["ระยอง", "rá-yoong", "Rayong (province/city)", "noun", "highway"],
  ["มาบตาพุด", "mâap-taa-phút", "Map Ta Phut (industrial port)", "noun", "highway"],
  ["บ้านฉาง", "bâan-chaang", "Ban Chang", "noun", "highway"],
  ["เขาชะเมา", "khǎo-chá-mao", "Khao Chamao (district/park)", "noun", "highway"],
  ["แกลง", "klaeng", "Klaeng (district town)", "noun", "highway"],
  ["บ้านค่าย", "bâan-khâai", "Ban Khai", "noun", "highway"],
  ["ปลวกแดง", "plùak-daeng", "Pluak Daeng (industrial area)", "noun", "highway"],
  ["นิคมอมตะซิตี้", "ní-khom-à-má-taa-sít-tîi", "Amata City industrial estate", "noun", "highway"],
  ["เกาะเสม็ด", "kò-sà-mèt", "Ko Samet (island)", "noun", "highway"],
  ["เขาใหญ่", "khǎo-yài", "Khao Yai (area/direction)", "noun", "highway"],
  ["ทางหลวงหมายเลข ๓", "thaang-lǔuang-mǎai-lêek-sǎam", "Highway 3 (Sukhumvit Rd)", "noun", "highway"],
  ["ถนนสุขุมวิท", "thà-nǒn-sù-khum-wít", "Sukhumvit Road (Hwy 3)", "noun", "highway"],
  ["มอเตอร์เวย์", "moo-tôoe-wee", "motorway (Bangkok–Pattaya)", "noun", "highway"],
  ["ทางพิเศษ", "thaang-phí-sèet", "special expressway", "noun", "highway"],
  ["อีอีซี", "ii-ii-sii", "EEC (Eastern Economic Corridor)", "noun", "highway"],

  // ─── Classroom Language ───────────────────────────────────────────────────
  ["อาจารย์", "aa-jaan", "professor/lecturer", "noun", "classroom"],
  ["การบ้าน", "gaan-bâan", "homework", "noun", "classroom"],
  ["คะแนน", "khá-naen", "score/marks", "noun", "classroom"],
  ["แบบฝึกหัด", "bàep-fùek-hàt", "worksheet/exercise", "noun", "classroom"],
  ["ทำซ้ำ", "tham-sâm", "to repeat", "verb", "classroom"],
  ["อีกครั้ง", "ìik-khráng", "one more time/again", "adverb", "classroom"],
  ["ผิด", "phìt", "wrong/incorrect", "adjective", "classroom"],
  ["ช้าๆ", "cháa-cháa", "slowly", "adverb", "classroom"],
  ["เงียบ", "ngîap", "quiet/silent", "adjective", "classroom"],
  ["ดีมาก", "dii-mâak", "very good/well done", "phrase", "classroom"],
  ["ต่อไป", "tòo-pai", "continue/next", "adverb", "classroom"],
  ["จดโน้ต", "jòt-nôot", "take notes", "phrase", "classroom"],
  ["ไม่เข้าใจ", "mâi-khâo-jai", "I don't understand", "phrase", "classroom"],
  ["พูดตามฉัน", "phûut-taam-chǎn", "repeat after me", "phrase", "classroom"],
  ["เติมในช่องว่าง", "toem-nai-chông-wâang", "fill in the blank", "phrase", "classroom"],
  ["เข้าใจไหม", "khâo-jai-mǎi", "do you understand?", "phrase", "classroom"],
  ["เปิดหนังสือ", "pòet-nǎng-sǔue", "open your book", "phrase", "classroom"],
  ["ปิดหนังสือ", "pìt-nǎng-sǔue", "close your book", "phrase", "classroom"],
  ["ถามได้เลย", "tǎam-dâi-looei", "feel free to ask", "phrase", "classroom"],
  ["ลองทำดู", "loong-tham-duu", "give it a try", "phrase", "classroom"],

  // ─── Love & Nightlife ─────────────────────────────────────────────────────
  ["แฟน", "faen", "boyfriend/girlfriend", "noun", "nightlife"],
  ["คนรัก", "khon-rák", "lover/sweetheart", "noun", "nightlife"],
  ["น่ารัก", "nâa-rák", "cute/adorable", "adjective", "nightlife"],
  ["จูบ", "jùup", "to kiss", "verb", "nightlife"],
  ["กอด", "gòot", "to hug", "verb", "nightlife"],
  ["หึง", "hǔeng", "jealous", "adjective", "nightlife"],
  ["เลิก", "lôoek", "to break up", "verb", "nightlife"],
  ["คิดถึง", "khít-thǔeng", "to miss someone", "verb", "nightlife"],
  ["ตกหลุมรัก", "tòk-lǔm-rák", "to fall in love", "verb", "nightlife"],
  ["ที่รัก", "thîi-rák", "darling/dear", "noun", "nightlife"],
  ["หลอก", "lòok", "to deceive/trick", "verb", "nightlife"],
  ["ทิ้ง", "thîng", "to abandon/dump", "verb", "nightlife"],
  ["บาร์", "baa", "bar", "noun", "nightlife"],
  ["โกโก้บาร์", "go-gôo-baa", "go-go bar", "noun", "nightlife"],
  ["บาร์ไฟน์", "baa-fain", "bar fine", "noun", "nightlife"],
  ["สาวบาร์", "sǎao-baa", "bar girl", "noun", "nightlife"],
  ["เลดี้ดริ้งค์", "lee-dtîi-drîng", "lady drink", "noun", "nightlife"],
  ["ฟรีแลนซ์", "frii-laen", "freelancer", "noun", "nightlife"],
  ["มาม่า", "maa-mâa", "mamasan/bar madam", "noun", "nightlife"],
  ["กะเทย", "gà-thoei", "ladyboy/transgender", "noun", "nightlife"],
  ["ฝรั่ง", "fà-ràng", "foreigner/Westerner", "noun", "nightlife"],
  ["เที่ยว", "thîao", "to go out/have fun", "verb", "nightlife"],
  ["เมา", "mao", "drunk", "adjective", "nightlife"],
  ["ว่าง", "wâang", "free/available", "adjective", "nightlife"],
  ["ถุงยาง", "thǔng-yaang", "condom", "noun", "nightlife"],
  ["ชอร์ตไทม์", "chôot-taim", "short time", "noun", "nightlife"],
  ["ลองไทม์", "loong-taim", "long time", "noun", "nightlife"],
  ["ร่วมรัก", "rûuam-rák", "to make love", "verb", "nightlife"],
  ["นอนด้วยกัน", "noon-dûay-gan", "sleep together", "phrase", "nightlife"],
  ["เปลือย", "bplooei", "naked", "adjective", "nightlife"],
  ["จ่าย", "jàai", "to pay", "verb", "nightlife"],
  ["ส่งเงิน", "sòng-ngoen", "to send money", "phrase", "nightlife"],
  ["คืนนี้", "khuuen-níi", "tonight", "adverb", "nightlife"],
  ["มีแฟนไหม", "mii-faen-mǎi", "do you have a partner?", "phrase", "nightlife"],
  ["ไม่มีแฟน", "mâi-mii-faen", "I'm single", "phrase", "nightlife"],
  ["ไปด้วยกันไหม", "pai-dûay-gan-mǎi", "shall we go together?", "phrase", "nightlife"],
  ["รักจริงไหม", "rák-jing-mǎi", "do you really love me?", "phrase", "nightlife"],
];

const TOP_100 = [
  "ที่",
  "ได้",
  "ไม่",
  "มี",
  "เป็น",
  "ใน",
  "และ",
  "จะ",
  "กับ",
  "ก็",
  "มา",
  "ไป",
  "นี้",
  "นั้น",
  "ของ",
  "ให้",
  "แล้ว",
  "จาก",
  "การ",
  "คน",
  "วัน",
  "เวลา",
  "บ้าน",
  "เงิน",
  "งาน",
  "ประเทศ",
  "เมือง",
  "ชีวิต",
  "ปี",
  "เดือน",
  "ทำ",
  "พูด",
  "บอก",
  "รู้",
  "เห็น",
  "คิด",
  "อยู่",
  "ต้อง",
  "ใช้",
  "รัก",
  "ชอบ",
  "กิน",
  "ดู",
  "ฟัง",
  "เข้าใจ",
  "อยาก",
  "ถาม",
  "ตอบ",
  "เริ่ม",
  "หยุด",
  "ดี",
  "ใหม่",
  "ใหญ่",
  "เล็ก",
  "มาก",
  "น้อย",
  "เร็ว",
  "ช้า",
  "ร้อน",
  "เย็น",
  "ง่าย",
  "ยาก",
  "ถูก",
  "แพง",
  "จริง",
  "สำคัญ",
  "ฉัน",
  "ผม",
  "คุณ",
  "เขา",
  "เรา",
  "อะไร",
  "ใคร",
  "ที่ไหน",
  "เมื่อไร",
  "ทำไม",
  "แต่",
  "หรือ",
  "เพราะ",
  "ถ้า",
  "ด้วย",
  "แค่",
  "ยัง",
  "ตอนนี้",
  "วันนี้",
  "พรุ่งนี้",
  "เมื่อวาน",
  "หนึ่ง",
  "สอง",
  "สาม",
  "สี่",
  "ห้า",
  "หก",
  "เจ็ด",
  "แปด",
  "เก้า",
  "สิบ",
  "น้ำ",
  "ข้าว",
  "รถ",
];

const TOP_50 = TOP_100.slice(0, 50);
const TOP_20 = TOP_100.slice(0, 20);

const CAT_LABELS = {
  "adjectives": "Adjectives",
  "adverbs": "Adverbs",
  "body": "Body",
  "colors": "Colors",
  "connectors": "Connectors & Prepositions",
  "education": "Education",
  "family": "Family",
  "food": "Food & Drink",
  "general": "General",
  "grammar": "Grammar",
  "health": "Health",
  "nature": "Nature & Weather",
  "numbers": "Numbers",
  "particles": "Particles",
  "phrases": "Phrases",
  "places": "Places",
  "pronouns": "Pronouns & Questions",
  "restaurant": "Restaurant & Menu",
  "highway": "Highway & Road Signs",
  "tech": "Technology",
  "time": "Time & Days",
  "verbs_aux": "Auxiliary Verbs",
  "verbs_core": "Core Verbs",
  "work": "Work & Business",
  "classroom": "Classroom Language",
  "nightlife": "Love & Nightlife",
};
