// Generates web/js/lexicon-th.js — the open-text word list behind Paste Text.
//
// WHY a second word list, when data.js already has one: the app's ~950-word
// curriculum map is the right tool inside the trainer, where the corpus is
// known, and the wrong one for arbitrary text. Greedy-matching a small map
// over open text produces confidently wrong segmentation — matching มา inside
// มาตรการ and glossing it "to come". See docs/chrome-extension-handoff.md §6.
//
// SOURCE (both CC0-1.0, created by the PyThaiNLP project):
//   words_th.txt  https://raw.githubusercontent.com/PyThaiNLP/pythainlp/dev/pythainlp/corpus/words_th.txt
//   tnc_freq.txt  https://raw.githubusercontent.com/PyThaiNLP/pythainlp/dev/pythainlp/corpus/tnc_freq.txt
//   licence       https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/corpus/corpus_license.md
//
// The generated file ships the list in DESCENDING FREQUENCY ORDER and nothing
// else — no counts. segment.js derives its Zipf cost from a word's rank, which
// measured within 0.5 F1 of using the real Thai National Corpus frequencies
// while halving the payload.
//
// Usage:
//   node scripts/build-lexicon.mjs <words_th.txt> <tnc_freq.txt>

import { readFileSync, writeFileSync } from "node:fs";
import vm from "node:vm";

// How many frequency-ranked words to keep. Measured against a 30-sentence
// out-of-curriculum gold set: 5k and 61k both score 95.5 boundary-F1, and the
// rare tail actively HURTS (61k drops to 95.0 — junk entries win bad matches).
// 12k is the headroom pick: identical score, more coverage of real-world text
// than the gold set exercises, ~220KB.
const KEEP = 12000;

const [, , wordsPath, freqPath] = process.argv;
if (!wordsPath || !freqPath) {
  console.error("usage: node scripts/build-lexicon.mjs <words_th.txt> <tnc_freq.txt>");
  console.error("see the header of this file for the two CC0 source URLs");
  process.exit(2);
}

// Curriculum words are ALWAYS kept, whatever their corpus frequency — the
// trainer must never fail to segment a word it teaches.
vm.runInThisContext(readFileSync(new URL("../web/js/data.js", import.meta.url), "utf8"));
const curriculum = WORDS.map(w => w[0]);

const thaiOnly = /^[฀-๿]+$/;
const lexicon = readFileSync(wordsPath, "utf8").split("\n").map(s => s.trim())
  // no spaces, no Latin, no digits; and drop bare single letters (ฆ ฏ ฒ are in
  // the source), which otherwise match everywhere and split real words
  .filter(w => thaiOnly.test(w) && [...w].length > 1);

const freq = new Map();
for (const line of readFileSync(freqPath, "utf8").split("\n")) {
  const [w, n] = line.split("\t");
  if (w && n) freq.set(w.trim(), +n);
}

const ranked = lexicon.slice().sort((a, b) => (freq.get(b) || 0) - (freq.get(a) || 0));
const out = ranked.slice(0, KEEP);
const have = new Set(out);
let added = 0;
for (const w of curriculum) {
  if (!have.has(w) && [...w].length > 1 && thaiOnly.test(w)) { out.push(w); have.add(w); added++; }
}

const body = out.join("\\n");
const maxLen = Math.max(...out.map(w => w.length));
writeFileSync(new URL("../web/js/lexicon-th.js", import.meta.url),
`// AUTO-GENERATED by scripts/build-lexicon.mjs — do not edit by hand.
// Open-text Thai word list for Paste Text, in descending frequency order.
// Source: PyThaiNLP words_th.txt + tnc_freq.txt, both CC0-1.0.
// https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/corpus/corpus_license.md
//
// ${out.length} words (top ${KEEP} by Thai National Corpus frequency, plus ${added}
// curriculum words that fell outside it). Longest entry: ${maxLen} chars.
//
// Loaded LAZILY by segment.js the first time Paste Text is opened — it is not
// in the service worker's PRECACHE, so it costs nothing until used, and the
// runtime cache keeps it available offline afterwards.
var THAI_LEXICON = "${body}";
`);
console.log(`wrote web/js/lexicon-th.js — ${out.length} words (${added} curriculum-only), maxlen ${maxLen}`);
